spring.application.name=VocabKickerServerless

# Serverless Optimizations
spring.main.lazy-initialization=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:604800000}

# AWS Configuration
aws.region=${AWS_REGION:ap-south-1}
aws.s3.import-bucket-name=${AWS_S3_IMPORT_BUCKET_NAME}

# Security / CORS Configuration
cors.allowed-origin=${CORS_ALLOWED_ORIGIN:https://vocabkicker.vercel.app}
